/**
 * Data seluruh Kabupaten/Kota di Indonesia (514 wilayah administrasi).
 *
 * Sumber: Badan Pusat Statistik (BPS) — dataset kode wilayah administrasi,
 * dinormalisasi ke format "Kabupaten/Kota <Nama>" dengan title case.
 *
 * File ini murni DATA — jangan taruh logic UI atau state di sini.
 * Reusable untuk: Register, Edit Profile, Dashboard, Ranking Nasional,
 * Ranking Kota, Statistik Pengguna, Filter Leaderboard, Analitik Wilayah.
 */

export type RegionType = "kabupaten" | "kota";

export interface IndonesiaRegion {
  /** Kode wilayah BPS (unik per kabupaten/kota) */
  id: string;
  /** Nilai yang disimpan ke database/form state, mis. "Kota Yogyakarta" */
  value: string;
  /** Teks yang ditampilkan ke pengguna (sama dengan value saat ini) */
  label: string;
  /** "kabupaten" | "kota" — berguna untuk filter/grouping di fitur lain */
  type: RegionType;
  /** Nama provinsi induk — berguna untuk analitik wilayah & grouping */
  province: string;
}

export const INDONESIA_REGIONS: IndonesiaRegion[] = [
  { id: "1107", value: "Kabupaten Aceh Barat", label: "Kabupaten Aceh Barat", type: "kabupaten", province: "Aceh" },
  { id: "1112", value: "Kabupaten Aceh Barat Daya", label: "Kabupaten Aceh Barat Daya", type: "kabupaten", province: "Aceh" },
  { id: "1108", value: "Kabupaten Aceh Besar", label: "Kabupaten Aceh Besar", type: "kabupaten", province: "Aceh" },
  { id: "1116", value: "Kabupaten Aceh Jaya", label: "Kabupaten Aceh Jaya", type: "kabupaten", province: "Aceh" },
  { id: "1103", value: "Kabupaten Aceh Selatan", label: "Kabupaten Aceh Selatan", type: "kabupaten", province: "Aceh" },
  { id: "1102", value: "Kabupaten Aceh Singkil", label: "Kabupaten Aceh Singkil", type: "kabupaten", province: "Aceh" },
  { id: "1114", value: "Kabupaten Aceh Tamiang", label: "Kabupaten Aceh Tamiang", type: "kabupaten", province: "Aceh" },
  { id: "1106", value: "Kabupaten Aceh Tengah", label: "Kabupaten Aceh Tengah", type: "kabupaten", province: "Aceh" },
  { id: "1104", value: "Kabupaten Aceh Tenggara", label: "Kabupaten Aceh Tenggara", type: "kabupaten", province: "Aceh" },
  { id: "1105", value: "Kabupaten Aceh Timur", label: "Kabupaten Aceh Timur", type: "kabupaten", province: "Aceh" },
  { id: "1111", value: "Kabupaten Aceh Utara", label: "Kabupaten Aceh Utara", type: "kabupaten", province: "Aceh" },
  { id: "1307", value: "Kabupaten Agam", label: "Kabupaten Agam", type: "kabupaten", province: "Sumatera Barat" },
  { id: "5307", value: "Kabupaten Alor", label: "Kabupaten Alor", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "1208", value: "Kabupaten Asahan", label: "Kabupaten Asahan", type: "kabupaten", province: "Sumatera Utara" },
  { id: "9415", value: "Kabupaten Asmat", label: "Kabupaten Asmat", type: "kabupaten", province: "Papua" },
  { id: "5103", value: "Kabupaten Badung", label: "Kabupaten Badung", type: "kabupaten", province: "Bali" },
  { id: "6311", value: "Kabupaten Balangan", label: "Kabupaten Balangan", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "3204", value: "Kabupaten Bandung", label: "Kabupaten Bandung", type: "kabupaten", province: "Jawa Barat" },
  { id: "3217", value: "Kabupaten Bandung Barat", label: "Kabupaten Bandung Barat", type: "kabupaten", province: "Jawa Barat" },
  { id: "7202", value: "Kabupaten Banggai", label: "Kabupaten Banggai", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "7201", value: "Kabupaten Banggai Kepulauan", label: "Kabupaten Banggai Kepulauan", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "7211", value: "Kabupaten Banggai Laut", label: "Kabupaten Banggai Laut", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "1901", value: "Kabupaten Bangka", label: "Kabupaten Bangka", type: "kabupaten", province: "Kepulauan Bangka Belitung" },
  { id: "1903", value: "Kabupaten Bangka Barat", label: "Kabupaten Bangka Barat", type: "kabupaten", province: "Kepulauan Bangka Belitung" },
  { id: "1905", value: "Kabupaten Bangka Selatan", label: "Kabupaten Bangka Selatan", type: "kabupaten", province: "Kepulauan Bangka Belitung" },
  { id: "1904", value: "Kabupaten Bangka Tengah", label: "Kabupaten Bangka Tengah", type: "kabupaten", province: "Kepulauan Bangka Belitung" },
  { id: "3526", value: "Kabupaten Bangkalan", label: "Kabupaten Bangkalan", type: "kabupaten", province: "Jawa Timur" },
  { id: "5106", value: "Kabupaten Bangli", label: "Kabupaten Bangli", type: "kabupaten", province: "Bali" },
  { id: "6303", value: "Kabupaten Banjar", label: "Kabupaten Banjar", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "3304", value: "Kabupaten Banjarnegara", label: "Kabupaten Banjarnegara", type: "kabupaten", province: "Jawa Tengah" },
  { id: "7303", value: "Kabupaten Bantaeng", label: "Kabupaten Bantaeng", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3402", value: "Kabupaten Bantul", label: "Kabupaten Bantul", type: "kabupaten", province: "DI Yogyakarta" },
  { id: "1607", value: "Kabupaten Banyu Asin", label: "Kabupaten Banyu Asin", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "3302", value: "Kabupaten Banyumas", label: "Kabupaten Banyumas", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3510", value: "Kabupaten Banyuwangi", label: "Kabupaten Banyuwangi", type: "kabupaten", province: "Jawa Timur" },
  { id: "6304", value: "Kabupaten Barito Kuala", label: "Kabupaten Barito Kuala", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "6204", value: "Kabupaten Barito Selatan", label: "Kabupaten Barito Selatan", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "6212", value: "Kabupaten Barito Timur", label: "Kabupaten Barito Timur", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "6205", value: "Kabupaten Barito Utara", label: "Kabupaten Barito Utara", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "7310", value: "Kabupaten Barru", label: "Kabupaten Barru", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3325", value: "Kabupaten Batang", label: "Kabupaten Batang", type: "kabupaten", province: "Jawa Tengah" },
  { id: "1504", value: "Kabupaten Batang Hari", label: "Kabupaten Batang Hari", type: "kabupaten", province: "Jambi" },
  { id: "1219", value: "Kabupaten Batu Bara", label: "Kabupaten Batu Bara", type: "kabupaten", province: "Sumatera Utara" },
  { id: "3216", value: "Kabupaten Bekasi", label: "Kabupaten Bekasi", type: "kabupaten", province: "Jawa Barat" },
  { id: "1902", value: "Kabupaten Belitung", label: "Kabupaten Belitung", type: "kabupaten", province: "Kepulauan Bangka Belitung" },
  { id: "1906", value: "Kabupaten Belitung Timur", label: "Kabupaten Belitung Timur", type: "kabupaten", province: "Kepulauan Bangka Belitung" },
  { id: "5306", value: "Kabupaten Belu", label: "Kabupaten Belu", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "1117", value: "Kabupaten Bener Meriah", label: "Kabupaten Bener Meriah", type: "kabupaten", province: "Aceh" },
  { id: "1408", value: "Kabupaten Bengkalis", label: "Kabupaten Bengkalis", type: "kabupaten", province: "Riau" },
  { id: "6102", value: "Kabupaten Bengkayang", label: "Kabupaten Bengkayang", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "1701", value: "Kabupaten Bengkulu Selatan", label: "Kabupaten Bengkulu Selatan", type: "kabupaten", province: "Bengkulu" },
  { id: "1709", value: "Kabupaten Bengkulu Tengah", label: "Kabupaten Bengkulu Tengah", type: "kabupaten", province: "Bengkulu" },
  { id: "1703", value: "Kabupaten Bengkulu Utara", label: "Kabupaten Bengkulu Utara", type: "kabupaten", province: "Bengkulu" },
  { id: "6405", value: "Kabupaten Berau", label: "Kabupaten Berau", type: "kabupaten", province: "Kalimantan Timur" },
  { id: "9409", value: "Kabupaten Biak Numfor", label: "Kabupaten Biak Numfor", type: "kabupaten", province: "Papua" },
  { id: "5206", value: "Kabupaten Bima", label: "Kabupaten Bima", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "2102", value: "Kabupaten Bintan", label: "Kabupaten Bintan", type: "kabupaten", province: "Kepulauan Riau" },
  { id: "1110", value: "Kabupaten Bireuen", label: "Kabupaten Bireuen", type: "kabupaten", province: "Aceh" },
  { id: "3505", value: "Kabupaten Blitar", label: "Kabupaten Blitar", type: "kabupaten", province: "Jawa Timur" },
  { id: "3316", value: "Kabupaten Blora", label: "Kabupaten Blora", type: "kabupaten", province: "Jawa Tengah" },
  { id: "7501", value: "Kabupaten Boalemo", label: "Kabupaten Boalemo", type: "kabupaten", province: "Gorontalo" },
  { id: "3201", value: "Kabupaten Bogor", label: "Kabupaten Bogor", type: "kabupaten", province: "Jawa Barat" },
  { id: "3522", value: "Kabupaten Bojonegoro", label: "Kabupaten Bojonegoro", type: "kabupaten", province: "Jawa Timur" },
  { id: "7101", value: "Kabupaten Bolaang Mongondow", label: "Kabupaten Bolaang Mongondow", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7110", value: "Kabupaten Bolaang Mongondow Selatan", label: "Kabupaten Bolaang Mongondow Selatan", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7111", value: "Kabupaten Bolaang Mongondow Timur", label: "Kabupaten Bolaang Mongondow Timur", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7107", value: "Kabupaten Bolaang Mongondow Utara", label: "Kabupaten Bolaang Mongondow Utara", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7406", value: "Kabupaten Bombana", label: "Kabupaten Bombana", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "3511", value: "Kabupaten Bondowoso", label: "Kabupaten Bondowoso", type: "kabupaten", province: "Jawa Timur" },
  { id: "7311", value: "Kabupaten Bone", label: "Kabupaten Bone", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "7504", value: "Kabupaten Bone Bolango", label: "Kabupaten Bone Bolango", type: "kabupaten", province: "Gorontalo" },
  { id: "9413", value: "Kabupaten Boven Digoel", label: "Kabupaten Boven Digoel", type: "kabupaten", province: "Papua" },
  { id: "3309", value: "Kabupaten Boyolali", label: "Kabupaten Boyolali", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3329", value: "Kabupaten Brebes", label: "Kabupaten Brebes", type: "kabupaten", province: "Jawa Tengah" },
  { id: "5108", value: "Kabupaten Buleleng", label: "Kabupaten Buleleng", type: "kabupaten", province: "Bali" },
  { id: "7302", value: "Kabupaten Bulukumba", label: "Kabupaten Bulukumba", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "6502", value: "Kabupaten Bulungan", label: "Kabupaten Bulungan", type: "kabupaten", province: "Kalimantan Utara" },
  { id: "1509", value: "Kabupaten Bungo", label: "Kabupaten Bungo", type: "kabupaten", province: "Jambi" },
  { id: "7207", value: "Kabupaten Buol", label: "Kabupaten Buol", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "8104", value: "Kabupaten Buru", label: "Kabupaten Buru", type: "kabupaten", province: "Maluku" },
  { id: "8109", value: "Kabupaten Buru Selatan", label: "Kabupaten Buru Selatan", type: "kabupaten", province: "Maluku" },
  { id: "7401", value: "Kabupaten Buton", label: "Kabupaten Buton", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7415", value: "Kabupaten Buton Selatan", label: "Kabupaten Buton Selatan", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7414", value: "Kabupaten Buton Tengah", label: "Kabupaten Buton Tengah", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7409", value: "Kabupaten Buton Utara", label: "Kabupaten Buton Utara", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "3207", value: "Kabupaten Ciamis", label: "Kabupaten Ciamis", type: "kabupaten", province: "Jawa Barat" },
  { id: "3203", value: "Kabupaten Cianjur", label: "Kabupaten Cianjur", type: "kabupaten", province: "Jawa Barat" },
  { id: "3301", value: "Kabupaten Cilacap", label: "Kabupaten Cilacap", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3209", value: "Kabupaten Cirebon", label: "Kabupaten Cirebon", type: "kabupaten", province: "Jawa Barat" },
  { id: "1210", value: "Kabupaten Dairi", label: "Kabupaten Dairi", type: "kabupaten", province: "Sumatera Utara" },
  { id: "9436", value: "Kabupaten Deiyai", label: "Kabupaten Deiyai", type: "kabupaten", province: "Papua" },
  { id: "1212", value: "Kabupaten Deli Serdang", label: "Kabupaten Deli Serdang", type: "kabupaten", province: "Sumatera Utara" },
  { id: "3321", value: "Kabupaten Demak", label: "Kabupaten Demak", type: "kabupaten", province: "Jawa Tengah" },
  { id: "1311", value: "Kabupaten Dharmasraya", label: "Kabupaten Dharmasraya", type: "kabupaten", province: "Sumatera Barat" },
  { id: "9434", value: "Kabupaten Dogiyai", label: "Kabupaten Dogiyai", type: "kabupaten", province: "Papua" },
  { id: "5205", value: "Kabupaten Dompu", label: "Kabupaten Dompu", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "7205", value: "Kabupaten Donggala", label: "Kabupaten Donggala", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "1611", value: "Kabupaten Empat Lawang", label: "Kabupaten Empat Lawang", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "5311", value: "Kabupaten Ende", label: "Kabupaten Ende", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "7316", value: "Kabupaten Enrekang", label: "Kabupaten Enrekang", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "9101", value: "Kabupaten Fak-fak", label: "Kabupaten Fak-fak", type: "kabupaten", province: "Papua Barat" },
  { id: "5309", value: "Kabupaten Flores Timur", label: "Kabupaten Flores Timur", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "3205", value: "Kabupaten Garut", label: "Kabupaten Garut", type: "kabupaten", province: "Jawa Barat" },
  { id: "1113", value: "Kabupaten Gayo Lues", label: "Kabupaten Gayo Lues", type: "kabupaten", province: "Aceh" },
  { id: "5104", value: "Kabupaten Gianyar", label: "Kabupaten Gianyar", type: "kabupaten", province: "Bali" },
  { id: "7502", value: "Kabupaten Gorontalo", label: "Kabupaten Gorontalo", type: "kabupaten", province: "Gorontalo" },
  { id: "7505", value: "Kabupaten Gorontalo Utara", label: "Kabupaten Gorontalo Utara", type: "kabupaten", province: "Gorontalo" },
  { id: "7306", value: "Kabupaten Gowa", label: "Kabupaten Gowa", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3525", value: "Kabupaten Gresik", label: "Kabupaten Gresik", type: "kabupaten", province: "Jawa Timur" },
  { id: "3315", value: "Kabupaten Grobogan", label: "Kabupaten Grobogan", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3403", value: "Kabupaten Gunung Kidul", label: "Kabupaten Gunung Kidul", type: "kabupaten", province: "DI Yogyakarta" },
  { id: "6211", value: "Kabupaten Gunung Mas", label: "Kabupaten Gunung Mas", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "8201", value: "Kabupaten Halmahera Barat", label: "Kabupaten Halmahera Barat", type: "kabupaten", province: "Maluku Utara" },
  { id: "8204", value: "Kabupaten Halmahera Selatan", label: "Kabupaten Halmahera Selatan", type: "kabupaten", province: "Maluku Utara" },
  { id: "8202", value: "Kabupaten Halmahera Tengah", label: "Kabupaten Halmahera Tengah", type: "kabupaten", province: "Maluku Utara" },
  { id: "8206", value: "Kabupaten Halmahera Timur", label: "Kabupaten Halmahera Timur", type: "kabupaten", province: "Maluku Utara" },
  { id: "8205", value: "Kabupaten Halmahera Utara", label: "Kabupaten Halmahera Utara", type: "kabupaten", province: "Maluku Utara" },
  { id: "6306", value: "Kabupaten Hulu Sungai Selatan", label: "Kabupaten Hulu Sungai Selatan", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "6307", value: "Kabupaten Hulu Sungai Tengah", label: "Kabupaten Hulu Sungai Tengah", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "6308", value: "Kabupaten Hulu Sungai Utara", label: "Kabupaten Hulu Sungai Utara", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "1215", value: "Kabupaten Humbang Hasundutan", label: "Kabupaten Humbang Hasundutan", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1403", value: "Kabupaten Indragiri Hilir", label: "Kabupaten Indragiri Hilir", type: "kabupaten", province: "Riau" },
  { id: "1402", value: "Kabupaten Indragiri Hulu", label: "Kabupaten Indragiri Hulu", type: "kabupaten", province: "Riau" },
  { id: "3212", value: "Kabupaten Indramayu", label: "Kabupaten Indramayu", type: "kabupaten", province: "Jawa Barat" },
  { id: "9435", value: "Kabupaten Intan Jaya", label: "Kabupaten Intan Jaya", type: "kabupaten", province: "Papua" },
  { id: "9403", value: "Kabupaten Jayapura", label: "Kabupaten Jayapura", type: "kabupaten", province: "Papua" },
  { id: "9402", value: "Kabupaten Jayawijaya", label: "Kabupaten Jayawijaya", type: "kabupaten", province: "Papua" },
  { id: "3509", value: "Kabupaten Jember", label: "Kabupaten Jember", type: "kabupaten", province: "Jawa Timur" },
  { id: "5101", value: "Kabupaten Jembrana", label: "Kabupaten Jembrana", type: "kabupaten", province: "Bali" },
  { id: "7304", value: "Kabupaten Jeneponto", label: "Kabupaten Jeneponto", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3320", value: "Kabupaten Jepara", label: "Kabupaten Jepara", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3517", value: "Kabupaten Jombang", label: "Kabupaten Jombang", type: "kabupaten", province: "Jawa Timur" },
  { id: "9102", value: "Kabupaten Kaimana", label: "Kabupaten Kaimana", type: "kabupaten", province: "Papua Barat" },
  { id: "1406", value: "Kabupaten Kampar", label: "Kabupaten Kampar", type: "kabupaten", province: "Riau" },
  { id: "6203", value: "Kabupaten Kapuas", label: "Kabupaten Kapuas", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "6108", value: "Kabupaten Kapuas Hulu", label: "Kabupaten Kapuas Hulu", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "5107", value: "Kabupaten Karang Asem", label: "Kabupaten Karang Asem", type: "kabupaten", province: "Bali" },
  { id: "3313", value: "Kabupaten Karanganyar", label: "Kabupaten Karanganyar", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3215", value: "Kabupaten Karawang", label: "Kabupaten Karawang", type: "kabupaten", province: "Jawa Barat" },
  { id: "2101", value: "Kabupaten Karimun", label: "Kabupaten Karimun", type: "kabupaten", province: "Kepulauan Riau" },
  { id: "1211", value: "Kabupaten Karo", label: "Kabupaten Karo", type: "kabupaten", province: "Sumatera Utara" },
  { id: "6209", value: "Kabupaten Katingan", label: "Kabupaten Katingan", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "1704", value: "Kabupaten Kaur", label: "Kabupaten Kaur", type: "kabupaten", province: "Bengkulu" },
  { id: "6111", value: "Kabupaten Kayong Utara", label: "Kabupaten Kayong Utara", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "3305", value: "Kabupaten Kebumen", label: "Kabupaten Kebumen", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3506", value: "Kabupaten Kediri", label: "Kabupaten Kediri", type: "kabupaten", province: "Jawa Timur" },
  { id: "9420", value: "Kabupaten Keerom", label: "Kabupaten Keerom", type: "kabupaten", province: "Papua" },
  { id: "3324", value: "Kabupaten Kendal", label: "Kabupaten Kendal", type: "kabupaten", province: "Jawa Tengah" },
  { id: "1708", value: "Kabupaten Kepahiang", label: "Kabupaten Kepahiang", type: "kabupaten", province: "Bengkulu" },
  { id: "2105", value: "Kabupaten Kepulauan Anambas", label: "Kabupaten Kepulauan Anambas", type: "kabupaten", province: "Kepulauan Riau" },
  { id: "8105", value: "Kabupaten Kepulauan Aru", label: "Kabupaten Kepulauan Aru", type: "kabupaten", province: "Maluku" },
  { id: "1301", value: "Kabupaten Kepulauan Mentawai", label: "Kabupaten Kepulauan Mentawai", type: "kabupaten", province: "Sumatera Barat" },
  { id: "1410", value: "Kabupaten Kepulauan Meranti", label: "Kabupaten Kepulauan Meranti", type: "kabupaten", province: "Riau" },
  { id: "7103", value: "Kabupaten Kepulauan Sangihe", label: "Kabupaten Kepulauan Sangihe", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7301", value: "Kabupaten Kepulauan Selayar", label: "Kabupaten Kepulauan Selayar", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3101", value: "Kabupaten Kepulauan Seribu", label: "Kabupaten Kepulauan Seribu", type: "kabupaten", province: "DKI Jakarta" },
  { id: "8203", value: "Kabupaten Kepulauan Sula", label: "Kabupaten Kepulauan Sula", type: "kabupaten", province: "Maluku Utara" },
  { id: "7104", value: "Kabupaten Kepulauan Talaud", label: "Kabupaten Kepulauan Talaud", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "9408", value: "Kabupaten Kepulauan Yapen", label: "Kabupaten Kepulauan Yapen", type: "kabupaten", province: "Papua" },
  { id: "1501", value: "Kabupaten Kerinci", label: "Kabupaten Kerinci", type: "kabupaten", province: "Jambi" },
  { id: "6106", value: "Kabupaten Ketapang", label: "Kabupaten Ketapang", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "3310", value: "Kabupaten Klaten", label: "Kabupaten Klaten", type: "kabupaten", province: "Jawa Tengah" },
  { id: "5105", value: "Kabupaten Klungkung", label: "Kabupaten Klungkung", type: "kabupaten", province: "Bali" },
  { id: "7404", value: "Kabupaten Kolaka", label: "Kabupaten Kolaka", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7411", value: "Kabupaten Kolaka Timur", label: "Kabupaten Kolaka Timur", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7408", value: "Kabupaten Kolaka Utara", label: "Kabupaten Kolaka Utara", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7403", value: "Kabupaten Konawe", label: "Kabupaten Konawe", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7412", value: "Kabupaten Konawe Kepulauan", label: "Kabupaten Konawe Kepulauan", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7405", value: "Kabupaten Konawe Selatan", label: "Kabupaten Konawe Selatan", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7410", value: "Kabupaten Konawe Utara", label: "Kabupaten Konawe Utara", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "6302", value: "Kabupaten Kota Baru", label: "Kabupaten Kota Baru", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "6201", value: "Kabupaten Kotawaringin Barat", label: "Kabupaten Kotawaringin Barat", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "6202", value: "Kabupaten Kotawaringin Timur", label: "Kabupaten Kotawaringin Timur", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "1401", value: "Kabupaten Kuantan Singingi", label: "Kabupaten Kuantan Singingi", type: "kabupaten", province: "Riau" },
  { id: "6112", value: "Kabupaten Kubu Raya", label: "Kabupaten Kubu Raya", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "3319", value: "Kabupaten Kudus", label: "Kabupaten Kudus", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3401", value: "Kabupaten Kulon Progo", label: "Kabupaten Kulon Progo", type: "kabupaten", province: "DI Yogyakarta" },
  { id: "3208", value: "Kabupaten Kuningan", label: "Kabupaten Kuningan", type: "kabupaten", province: "Jawa Barat" },
  { id: "5303", value: "Kabupaten Kupang", label: "Kabupaten Kupang", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "6402", value: "Kabupaten Kutai Barat", label: "Kabupaten Kutai Barat", type: "kabupaten", province: "Kalimantan Timur" },
  { id: "6403", value: "Kabupaten Kutai Kartanegara", label: "Kabupaten Kutai Kartanegara", type: "kabupaten", province: "Kalimantan Timur" },
  { id: "6404", value: "Kabupaten Kutai Timur", label: "Kabupaten Kutai Timur", type: "kabupaten", province: "Kalimantan Timur" },
  { id: "1207", value: "Kabupaten Labuhan Batu", label: "Kabupaten Labuhan Batu", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1222", value: "Kabupaten Labuhan Batu Selatan", label: "Kabupaten Labuhan Batu Selatan", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1223", value: "Kabupaten Labuhan Batu Utara", label: "Kabupaten Labuhan Batu Utara", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1604", value: "Kabupaten Lahat", label: "Kabupaten Lahat", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "6207", value: "Kabupaten Lamandau", label: "Kabupaten Lamandau", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "3524", value: "Kabupaten Lamongan", label: "Kabupaten Lamongan", type: "kabupaten", province: "Jawa Timur" },
  { id: "1801", value: "Kabupaten Lampung Barat", label: "Kabupaten Lampung Barat", type: "kabupaten", province: "Lampung" },
  { id: "1803", value: "Kabupaten Lampung Selatan", label: "Kabupaten Lampung Selatan", type: "kabupaten", province: "Lampung" },
  { id: "1805", value: "Kabupaten Lampung Tengah", label: "Kabupaten Lampung Tengah", type: "kabupaten", province: "Lampung" },
  { id: "1804", value: "Kabupaten Lampung Timur", label: "Kabupaten Lampung Timur", type: "kabupaten", province: "Lampung" },
  { id: "1806", value: "Kabupaten Lampung Utara", label: "Kabupaten Lampung Utara", type: "kabupaten", province: "Lampung" },
  { id: "6103", value: "Kabupaten Landak", label: "Kabupaten Landak", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "1213", value: "Kabupaten Langkat", label: "Kabupaten Langkat", type: "kabupaten", province: "Sumatera Utara" },
  { id: "9430", value: "Kabupaten Lanny Jaya", label: "Kabupaten Lanny Jaya", type: "kabupaten", province: "Papua" },
  { id: "3602", value: "Kabupaten Lebak", label: "Kabupaten Lebak", type: "kabupaten", province: "Banten" },
  { id: "1707", value: "Kabupaten Lebong", label: "Kabupaten Lebong", type: "kabupaten", province: "Bengkulu" },
  { id: "5308", value: "Kabupaten Lembata", label: "Kabupaten Lembata", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "1308", value: "Kabupaten Lima Puluh Kota", label: "Kabupaten Lima Puluh Kota", type: "kabupaten", province: "Sumatera Barat" },
  { id: "2104", value: "Kabupaten Lingga", label: "Kabupaten Lingga", type: "kabupaten", province: "Kepulauan Riau" },
  { id: "5201", value: "Kabupaten Lombok Barat", label: "Kabupaten Lombok Barat", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "5202", value: "Kabupaten Lombok Tengah", label: "Kabupaten Lombok Tengah", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "5203", value: "Kabupaten Lombok Timur", label: "Kabupaten Lombok Timur", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "5208", value: "Kabupaten Lombok Utara", label: "Kabupaten Lombok Utara", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "3508", value: "Kabupaten Lumajang", label: "Kabupaten Lumajang", type: "kabupaten", province: "Jawa Timur" },
  { id: "7317", value: "Kabupaten Luwu", label: "Kabupaten Luwu", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "7325", value: "Kabupaten Luwu Timur", label: "Kabupaten Luwu Timur", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "7322", value: "Kabupaten Luwu Utara", label: "Kabupaten Luwu Utara", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3519", value: "Kabupaten Madiun", label: "Kabupaten Madiun", type: "kabupaten", province: "Jawa Timur" },
  { id: "3308", value: "Kabupaten Magelang", label: "Kabupaten Magelang", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3520", value: "Kabupaten Magetan", label: "Kabupaten Magetan", type: "kabupaten", province: "Jawa Timur" },
  { id: "6411", value: "Kabupaten Mahakam Hulu", label: "Kabupaten Mahakam Hulu", type: "kabupaten", province: "Kalimantan Timur" },
  { id: "3210", value: "Kabupaten Majalengka", label: "Kabupaten Majalengka", type: "kabupaten", province: "Jawa Barat" },
  { id: "7601", value: "Kabupaten Majene", label: "Kabupaten Majene", type: "kabupaten", province: "Sulawesi Barat" },
  { id: "5321", value: "Kabupaten Malaka", label: "Kabupaten Malaka", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "3507", value: "Kabupaten Malang", label: "Kabupaten Malang", type: "kabupaten", province: "Jawa Timur" },
  { id: "6501", value: "Kabupaten Malinau", label: "Kabupaten Malinau", type: "kabupaten", province: "Kalimantan Utara" },
  { id: "8108", value: "Kabupaten Maluku Barat Daya", label: "Kabupaten Maluku Barat Daya", type: "kabupaten", province: "Maluku" },
  { id: "8103", value: "Kabupaten Maluku Tengah", label: "Kabupaten Maluku Tengah", type: "kabupaten", province: "Maluku" },
  { id: "8102", value: "Kabupaten Maluku Tenggara", label: "Kabupaten Maluku Tenggara", type: "kabupaten", province: "Maluku" },
  { id: "8101", value: "Kabupaten Maluku Tenggara Barat", label: "Kabupaten Maluku Tenggara Barat", type: "kabupaten", province: "Maluku" },
  { id: "7603", value: "Kabupaten Mamasa", label: "Kabupaten Mamasa", type: "kabupaten", province: "Sulawesi Barat" },
  { id: "9428", value: "Kabupaten Mamberamo Raya", label: "Kabupaten Mamberamo Raya", type: "kabupaten", province: "Papua" },
  { id: "9431", value: "Kabupaten Mamberamo Tengah", label: "Kabupaten Mamberamo Tengah", type: "kabupaten", province: "Papua" },
  { id: "7604", value: "Kabupaten Mamuju", label: "Kabupaten Mamuju", type: "kabupaten", province: "Sulawesi Barat" },
  { id: "7606", value: "Kabupaten Mamuju Tengah", label: "Kabupaten Mamuju Tengah", type: "kabupaten", province: "Sulawesi Barat" },
  { id: "7605", value: "Kabupaten Mamuju Utara", label: "Kabupaten Mamuju Utara", type: "kabupaten", province: "Sulawesi Barat" },
  { id: "1202", value: "Kabupaten Mandailing Natal", label: "Kabupaten Mandailing Natal", type: "kabupaten", province: "Sumatera Utara" },
  { id: "5313", value: "Kabupaten Manggarai", label: "Kabupaten Manggarai", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5315", value: "Kabupaten Manggarai Barat", label: "Kabupaten Manggarai Barat", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5319", value: "Kabupaten Manggarai Timur", label: "Kabupaten Manggarai Timur", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "9105", value: "Kabupaten Manokwari", label: "Kabupaten Manokwari", type: "kabupaten", province: "Papua Barat" },
  { id: "9111", value: "Kabupaten Manokwari Selatan", label: "Kabupaten Manokwari Selatan", type: "kabupaten", province: "Papua Barat" },
  { id: "9414", value: "Kabupaten Mappi", label: "Kabupaten Mappi", type: "kabupaten", province: "Papua" },
  { id: "7308", value: "Kabupaten Maros", label: "Kabupaten Maros", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "9110", value: "Kabupaten Maybrat", label: "Kabupaten Maybrat", type: "kabupaten", province: "Papua Barat" },
  { id: "6110", value: "Kabupaten Melawi", label: "Kabupaten Melawi", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "6104", value: "Kabupaten Mempawah", label: "Kabupaten Mempawah", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "1502", value: "Kabupaten Merangin", label: "Kabupaten Merangin", type: "kabupaten", province: "Jambi" },
  { id: "9401", value: "Kabupaten Merauke", label: "Kabupaten Merauke", type: "kabupaten", province: "Papua" },
  { id: "1811", value: "Kabupaten Mesuji", label: "Kabupaten Mesuji", type: "kabupaten", province: "Lampung" },
  { id: "9412", value: "Kabupaten Mimika", label: "Kabupaten Mimika", type: "kabupaten", province: "Papua" },
  { id: "7102", value: "Kabupaten Minahasa", label: "Kabupaten Minahasa", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7105", value: "Kabupaten Minahasa Selatan", label: "Kabupaten Minahasa Selatan", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7109", value: "Kabupaten Minahasa Tenggara", label: "Kabupaten Minahasa Tenggara", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7106", value: "Kabupaten Minahasa Utara", label: "Kabupaten Minahasa Utara", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "3516", value: "Kabupaten Mojokerto", label: "Kabupaten Mojokerto", type: "kabupaten", province: "Jawa Timur" },
  { id: "7203", value: "Kabupaten Morowali", label: "Kabupaten Morowali", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "7212", value: "Kabupaten Morowali Utara", label: "Kabupaten Morowali Utara", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "1603", value: "Kabupaten Muara Enim", label: "Kabupaten Muara Enim", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1505", value: "Kabupaten Muaro Jambi", label: "Kabupaten Muaro Jambi", type: "kabupaten", province: "Jambi" },
  { id: "1706", value: "Kabupaten Mukomuko", label: "Kabupaten Mukomuko", type: "kabupaten", province: "Bengkulu" },
  { id: "7402", value: "Kabupaten Muna", label: "Kabupaten Muna", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "7413", value: "Kabupaten Muna Barat", label: "Kabupaten Muna Barat", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "6213", value: "Kabupaten Murung Raya", label: "Kabupaten Murung Raya", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "1606", value: "Kabupaten Musi Banyu Asin", label: "Kabupaten Musi Banyu Asin", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1605", value: "Kabupaten Musi Rawas", label: "Kabupaten Musi Rawas", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1613", value: "Kabupaten Musi Rawas Utara", label: "Kabupaten Musi Rawas Utara", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "9404", value: "Kabupaten Nabire", label: "Kabupaten Nabire", type: "kabupaten", province: "Papua" },
  { id: "1115", value: "Kabupaten Nagan Raya", label: "Kabupaten Nagan Raya", type: "kabupaten", province: "Aceh" },
  { id: "5318", value: "Kabupaten Nagekeo", label: "Kabupaten Nagekeo", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "2103", value: "Kabupaten Natuna", label: "Kabupaten Natuna", type: "kabupaten", province: "Kepulauan Riau" },
  { id: "9429", value: "Kabupaten Nduga", label: "Kabupaten Nduga", type: "kabupaten", province: "Papua" },
  { id: "5312", value: "Kabupaten Ngada", label: "Kabupaten Ngada", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "3518", value: "Kabupaten Nganjuk", label: "Kabupaten Nganjuk", type: "kabupaten", province: "Jawa Timur" },
  { id: "3521", value: "Kabupaten Ngawi", label: "Kabupaten Ngawi", type: "kabupaten", province: "Jawa Timur" },
  { id: "1201", value: "Kabupaten Nias", label: "Kabupaten Nias", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1225", value: "Kabupaten Nias Barat", label: "Kabupaten Nias Barat", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1214", value: "Kabupaten Nias Selatan", label: "Kabupaten Nias Selatan", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1224", value: "Kabupaten Nias Utara", label: "Kabupaten Nias Utara", type: "kabupaten", province: "Sumatera Utara" },
  { id: "6504", value: "Kabupaten Nunukan", label: "Kabupaten Nunukan", type: "kabupaten", province: "Kalimantan Utara" },
  { id: "1610", value: "Kabupaten Ogan Ilir", label: "Kabupaten Ogan Ilir", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1602", value: "Kabupaten Ogan Komering Ilir", label: "Kabupaten Ogan Komering Ilir", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1601", value: "Kabupaten Ogan Komering Ulu", label: "Kabupaten Ogan Komering Ulu", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1608", value: "Kabupaten Ogan Komering Ulu Selatan", label: "Kabupaten Ogan Komering Ulu Selatan", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1609", value: "Kabupaten Ogan Komering Ulu Timur", label: "Kabupaten Ogan Komering Ulu Timur", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "3501", value: "Kabupaten Pacitan", label: "Kabupaten Pacitan", type: "kabupaten", province: "Jawa Timur" },
  { id: "1221", value: "Kabupaten Padang Lawas", label: "Kabupaten Padang Lawas", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1220", value: "Kabupaten Padang Lawas Utara", label: "Kabupaten Padang Lawas Utara", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1306", value: "Kabupaten Padang Pariaman", label: "Kabupaten Padang Pariaman", type: "kabupaten", province: "Sumatera Barat" },
  { id: "1216", value: "Kabupaten Pakpak Bharat", label: "Kabupaten Pakpak Bharat", type: "kabupaten", province: "Sumatera Utara" },
  { id: "3528", value: "Kabupaten Pamekasan", label: "Kabupaten Pamekasan", type: "kabupaten", province: "Jawa Timur" },
  { id: "3601", value: "Kabupaten Pandeglang", label: "Kabupaten Pandeglang", type: "kabupaten", province: "Banten" },
  { id: "3218", value: "Kabupaten Pangandaran", label: "Kabupaten Pangandaran", type: "kabupaten", province: "Jawa Barat" },
  { id: "7309", value: "Kabupaten Pangkajene Dan Kepulauan", label: "Kabupaten Pangkajene Dan Kepulauan", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "9410", value: "Kabupaten Paniai", label: "Kabupaten Paniai", type: "kabupaten", province: "Papua" },
  { id: "7208", value: "Kabupaten Parigi Moutong", label: "Kabupaten Parigi Moutong", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "1309", value: "Kabupaten Pasaman", label: "Kabupaten Pasaman", type: "kabupaten", province: "Sumatera Barat" },
  { id: "1312", value: "Kabupaten Pasaman Barat", label: "Kabupaten Pasaman Barat", type: "kabupaten", province: "Sumatera Barat" },
  { id: "6401", value: "Kabupaten Paser", label: "Kabupaten Paser", type: "kabupaten", province: "Kalimantan Timur" },
  { id: "3514", value: "Kabupaten Pasuruan", label: "Kabupaten Pasuruan", type: "kabupaten", province: "Jawa Timur" },
  { id: "3318", value: "Kabupaten Pati", label: "Kabupaten Pati", type: "kabupaten", province: "Jawa Tengah" },
  { id: "9112", value: "Kabupaten Pegunungan Arfak", label: "Kabupaten Pegunungan Arfak", type: "kabupaten", province: "Papua Barat" },
  { id: "9417", value: "Kabupaten Pegunungan Bintang", label: "Kabupaten Pegunungan Bintang", type: "kabupaten", province: "Papua" },
  { id: "3326", value: "Kabupaten Pekalongan", label: "Kabupaten Pekalongan", type: "kabupaten", province: "Jawa Tengah" },
  { id: "1404", value: "Kabupaten Pelalawan", label: "Kabupaten Pelalawan", type: "kabupaten", province: "Riau" },
  { id: "3327", value: "Kabupaten Pemalang", label: "Kabupaten Pemalang", type: "kabupaten", province: "Jawa Tengah" },
  { id: "6409", value: "Kabupaten Penajam Paser Utara", label: "Kabupaten Penajam Paser Utara", type: "kabupaten", province: "Kalimantan Timur" },
  { id: "1612", value: "Kabupaten Penukal Abab Lematang Ilir", label: "Kabupaten Penukal Abab Lematang Ilir", type: "kabupaten", province: "Sumatera Selatan" },
  { id: "1809", value: "Kabupaten Pesawaran", label: "Kabupaten Pesawaran", type: "kabupaten", province: "Lampung" },
  { id: "1813", value: "Kabupaten Pesisir Barat", label: "Kabupaten Pesisir Barat", type: "kabupaten", province: "Lampung" },
  { id: "1302", value: "Kabupaten Pesisir Selatan", label: "Kabupaten Pesisir Selatan", type: "kabupaten", province: "Sumatera Barat" },
  { id: "1109", value: "Kabupaten Pidie", label: "Kabupaten Pidie", type: "kabupaten", province: "Aceh" },
  { id: "1118", value: "Kabupaten Pidie Jaya", label: "Kabupaten Pidie Jaya", type: "kabupaten", province: "Aceh" },
  { id: "7315", value: "Kabupaten Pinrang", label: "Kabupaten Pinrang", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "7503", value: "Kabupaten Pohuwato", label: "Kabupaten Pohuwato", type: "kabupaten", province: "Gorontalo" },
  { id: "7602", value: "Kabupaten Polewali Mandar", label: "Kabupaten Polewali Mandar", type: "kabupaten", province: "Sulawesi Barat" },
  { id: "3502", value: "Kabupaten Ponorogo", label: "Kabupaten Ponorogo", type: "kabupaten", province: "Jawa Timur" },
  { id: "7204", value: "Kabupaten Poso", label: "Kabupaten Poso", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "1810", value: "Kabupaten Pringsewu", label: "Kabupaten Pringsewu", type: "kabupaten", province: "Lampung" },
  { id: "3513", value: "Kabupaten Probolinggo", label: "Kabupaten Probolinggo", type: "kabupaten", province: "Jawa Timur" },
  { id: "6210", value: "Kabupaten Pulang Pisau", label: "Kabupaten Pulang Pisau", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "8207", value: "Kabupaten Pulau Morotai", label: "Kabupaten Pulau Morotai", type: "kabupaten", province: "Maluku Utara" },
  { id: "8208", value: "Kabupaten Pulau Taliabu", label: "Kabupaten Pulau Taliabu", type: "kabupaten", province: "Maluku Utara" },
  { id: "9433", value: "Kabupaten Puncak", label: "Kabupaten Puncak", type: "kabupaten", province: "Papua" },
  { id: "9411", value: "Kabupaten Puncak Jaya", label: "Kabupaten Puncak Jaya", type: "kabupaten", province: "Papua" },
  { id: "3303", value: "Kabupaten Purbalingga", label: "Kabupaten Purbalingga", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3214", value: "Kabupaten Purwakarta", label: "Kabupaten Purwakarta", type: "kabupaten", province: "Jawa Barat" },
  { id: "3306", value: "Kabupaten Purworejo", label: "Kabupaten Purworejo", type: "kabupaten", province: "Jawa Tengah" },
  { id: "9108", value: "Kabupaten Raja Ampat", label: "Kabupaten Raja Ampat", type: "kabupaten", province: "Papua Barat" },
  { id: "1702", value: "Kabupaten Rejang Lebong", label: "Kabupaten Rejang Lebong", type: "kabupaten", province: "Bengkulu" },
  { id: "3317", value: "Kabupaten Rembang", label: "Kabupaten Rembang", type: "kabupaten", province: "Jawa Tengah" },
  { id: "1409", value: "Kabupaten Rokan Hilir", label: "Kabupaten Rokan Hilir", type: "kabupaten", province: "Riau" },
  { id: "1407", value: "Kabupaten Rokan Hulu", label: "Kabupaten Rokan Hulu", type: "kabupaten", province: "Riau" },
  { id: "5314", value: "Kabupaten Rote Ndao", label: "Kabupaten Rote Ndao", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5320", value: "Kabupaten Sabu Raijua", label: "Kabupaten Sabu Raijua", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "6101", value: "Kabupaten Sambas", label: "Kabupaten Sambas", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "1217", value: "Kabupaten Samosir", label: "Kabupaten Samosir", type: "kabupaten", province: "Sumatera Utara" },
  { id: "3527", value: "Kabupaten Sampang", label: "Kabupaten Sampang", type: "kabupaten", province: "Jawa Timur" },
  { id: "6105", value: "Kabupaten Sanggau", label: "Kabupaten Sanggau", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "9419", value: "Kabupaten Sarmi", label: "Kabupaten Sarmi", type: "kabupaten", province: "Papua" },
  { id: "1503", value: "Kabupaten Sarolangun", label: "Kabupaten Sarolangun", type: "kabupaten", province: "Jambi" },
  { id: "6109", value: "Kabupaten Sekadau", label: "Kabupaten Sekadau", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "1705", value: "Kabupaten Seluma", label: "Kabupaten Seluma", type: "kabupaten", province: "Bengkulu" },
  { id: "3322", value: "Kabupaten Semarang", label: "Kabupaten Semarang", type: "kabupaten", province: "Jawa Tengah" },
  { id: "8106", value: "Kabupaten Seram Bagian Barat", label: "Kabupaten Seram Bagian Barat", type: "kabupaten", province: "Maluku" },
  { id: "8107", value: "Kabupaten Seram Bagian Timur", label: "Kabupaten Seram Bagian Timur", type: "kabupaten", province: "Maluku" },
  { id: "3604", value: "Kabupaten Serang", label: "Kabupaten Serang", type: "kabupaten", province: "Banten" },
  { id: "1218", value: "Kabupaten Serdang Bedagai", label: "Kabupaten Serdang Bedagai", type: "kabupaten", province: "Sumatera Utara" },
  { id: "6208", value: "Kabupaten Seruyan", label: "Kabupaten Seruyan", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "1405", value: "Kabupaten Siak", label: "Kabupaten Siak", type: "kabupaten", province: "Riau" },
  { id: "7108", value: "Kabupaten Siau Tagulandang Biaro", label: "Kabupaten Siau Tagulandang Biaro", type: "kabupaten", province: "Sulawesi Utara" },
  { id: "7314", value: "Kabupaten Sidenreng Rappang", label: "Kabupaten Sidenreng Rappang", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3515", value: "Kabupaten Sidoarjo", label: "Kabupaten Sidoarjo", type: "kabupaten", province: "Jawa Timur" },
  { id: "7210", value: "Kabupaten Sigi", label: "Kabupaten Sigi", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "1304", value: "Kabupaten Sijunjung", label: "Kabupaten Sijunjung", type: "kabupaten", province: "Sumatera Barat" },
  { id: "5310", value: "Kabupaten Sikka", label: "Kabupaten Sikka", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "1209", value: "Kabupaten Simalungun", label: "Kabupaten Simalungun", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1101", value: "Kabupaten Simeulue", label: "Kabupaten Simeulue", type: "kabupaten", province: "Aceh" },
  { id: "7307", value: "Kabupaten Sinjai", label: "Kabupaten Sinjai", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "6107", value: "Kabupaten Sintang", label: "Kabupaten Sintang", type: "kabupaten", province: "Kalimantan Barat" },
  { id: "3512", value: "Kabupaten Situbondo", label: "Kabupaten Situbondo", type: "kabupaten", province: "Jawa Timur" },
  { id: "3404", value: "Kabupaten Sleman", label: "Kabupaten Sleman", type: "kabupaten", province: "DI Yogyakarta" },
  { id: "1303", value: "Kabupaten Solok", label: "Kabupaten Solok", type: "kabupaten", province: "Sumatera Barat" },
  { id: "1310", value: "Kabupaten Solok Selatan", label: "Kabupaten Solok Selatan", type: "kabupaten", province: "Sumatera Barat" },
  { id: "7312", value: "Kabupaten Soppeng", label: "Kabupaten Soppeng", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "9107", value: "Kabupaten Sorong", label: "Kabupaten Sorong", type: "kabupaten", province: "Papua Barat" },
  { id: "9106", value: "Kabupaten Sorong Selatan", label: "Kabupaten Sorong Selatan", type: "kabupaten", province: "Papua Barat" },
  { id: "3314", value: "Kabupaten Sragen", label: "Kabupaten Sragen", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3213", value: "Kabupaten Subang", label: "Kabupaten Subang", type: "kabupaten", province: "Jawa Barat" },
  { id: "3202", value: "Kabupaten Sukabumi", label: "Kabupaten Sukabumi", type: "kabupaten", province: "Jawa Barat" },
  { id: "6206", value: "Kabupaten Sukamara", label: "Kabupaten Sukamara", type: "kabupaten", province: "Kalimantan Tengah" },
  { id: "3311", value: "Kabupaten Sukoharjo", label: "Kabupaten Sukoharjo", type: "kabupaten", province: "Jawa Tengah" },
  { id: "5301", value: "Kabupaten Sumba Barat", label: "Kabupaten Sumba Barat", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5317", value: "Kabupaten Sumba Barat Daya", label: "Kabupaten Sumba Barat Daya", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5316", value: "Kabupaten Sumba Tengah", label: "Kabupaten Sumba Tengah", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5302", value: "Kabupaten Sumba Timur", label: "Kabupaten Sumba Timur", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5204", value: "Kabupaten Sumbawa", label: "Kabupaten Sumbawa", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "5207", value: "Kabupaten Sumbawa Barat", label: "Kabupaten Sumbawa Barat", type: "kabupaten", province: "Nusa Tenggara Barat" },
  { id: "3211", value: "Kabupaten Sumedang", label: "Kabupaten Sumedang", type: "kabupaten", province: "Jawa Barat" },
  { id: "3529", value: "Kabupaten Sumenep", label: "Kabupaten Sumenep", type: "kabupaten", province: "Jawa Timur" },
  { id: "9427", value: "Kabupaten Supiori", label: "Kabupaten Supiori", type: "kabupaten", province: "Papua" },
  { id: "6309", value: "Kabupaten Tabalong", label: "Kabupaten Tabalong", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "5102", value: "Kabupaten Tabanan", label: "Kabupaten Tabanan", type: "kabupaten", province: "Bali" },
  { id: "7305", value: "Kabupaten Takalar", label: "Kabupaten Takalar", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "9109", value: "Kabupaten Tambrauw", label: "Kabupaten Tambrauw", type: "kabupaten", province: "Papua Barat" },
  { id: "6503", value: "Kabupaten Tana Tidung", label: "Kabupaten Tana Tidung", type: "kabupaten", province: "Kalimantan Utara" },
  { id: "7318", value: "Kabupaten Tana Toraja", label: "Kabupaten Tana Toraja", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "6310", value: "Kabupaten Tanah Bumbu", label: "Kabupaten Tanah Bumbu", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "1305", value: "Kabupaten Tanah Datar", label: "Kabupaten Tanah Datar", type: "kabupaten", province: "Sumatera Barat" },
  { id: "6301", value: "Kabupaten Tanah Laut", label: "Kabupaten Tanah Laut", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "3603", value: "Kabupaten Tangerang", label: "Kabupaten Tangerang", type: "kabupaten", province: "Banten" },
  { id: "1802", value: "Kabupaten Tanggamus", label: "Kabupaten Tanggamus", type: "kabupaten", province: "Lampung" },
  { id: "1507", value: "Kabupaten Tanjung Jabung Barat", label: "Kabupaten Tanjung Jabung Barat", type: "kabupaten", province: "Jambi" },
  { id: "1506", value: "Kabupaten Tanjung Jabung Timur", label: "Kabupaten Tanjung Jabung Timur", type: "kabupaten", province: "Jambi" },
  { id: "1203", value: "Kabupaten Tapanuli Selatan", label: "Kabupaten Tapanuli Selatan", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1204", value: "Kabupaten Tapanuli Tengah", label: "Kabupaten Tapanuli Tengah", type: "kabupaten", province: "Sumatera Utara" },
  { id: "1205", value: "Kabupaten Tapanuli Utara", label: "Kabupaten Tapanuli Utara", type: "kabupaten", province: "Sumatera Utara" },
  { id: "6305", value: "Kabupaten Tapin", label: "Kabupaten Tapin", type: "kabupaten", province: "Kalimantan Selatan" },
  { id: "3206", value: "Kabupaten Tasikmalaya", label: "Kabupaten Tasikmalaya", type: "kabupaten", province: "Jawa Barat" },
  { id: "1508", value: "Kabupaten Tebo", label: "Kabupaten Tebo", type: "kabupaten", province: "Jambi" },
  { id: "3328", value: "Kabupaten Tegal", label: "Kabupaten Tegal", type: "kabupaten", province: "Jawa Tengah" },
  { id: "9104", value: "Kabupaten Teluk Bintuni", label: "Kabupaten Teluk Bintuni", type: "kabupaten", province: "Papua Barat" },
  { id: "9103", value: "Kabupaten Teluk Wondama", label: "Kabupaten Teluk Wondama", type: "kabupaten", province: "Papua Barat" },
  { id: "3323", value: "Kabupaten Temanggung", label: "Kabupaten Temanggung", type: "kabupaten", province: "Jawa Tengah" },
  { id: "5304", value: "Kabupaten Timor Tengah Selatan", label: "Kabupaten Timor Tengah Selatan", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "5305", value: "Kabupaten Timor Tengah Utara", label: "Kabupaten Timor Tengah Utara", type: "kabupaten", province: "Nusa Tenggara Timur" },
  { id: "1206", value: "Kabupaten Toba Samosir", label: "Kabupaten Toba Samosir", type: "kabupaten", province: "Sumatera Utara" },
  { id: "7209", value: "Kabupaten Tojo Una-una", label: "Kabupaten Tojo Una-una", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "7206", value: "Kabupaten Toli-toli", label: "Kabupaten Toli-toli", type: "kabupaten", province: "Sulawesi Tengah" },
  { id: "9418", value: "Kabupaten Tolikara", label: "Kabupaten Tolikara", type: "kabupaten", province: "Papua" },
  { id: "7326", value: "Kabupaten Toraja Utara", label: "Kabupaten Toraja Utara", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "3503", value: "Kabupaten Trenggalek", label: "Kabupaten Trenggalek", type: "kabupaten", province: "Jawa Timur" },
  { id: "3523", value: "Kabupaten Tuban", label: "Kabupaten Tuban", type: "kabupaten", province: "Jawa Timur" },
  { id: "1812", value: "Kabupaten Tulang Bawang Barat", label: "Kabupaten Tulang Bawang Barat", type: "kabupaten", province: "Lampung" },
  { id: "1808", value: "Kabupaten Tulangbawang", label: "Kabupaten Tulangbawang", type: "kabupaten", province: "Lampung" },
  { id: "3504", value: "Kabupaten Tulungagung", label: "Kabupaten Tulungagung", type: "kabupaten", province: "Jawa Timur" },
  { id: "7313", value: "Kabupaten Wajo", label: "Kabupaten Wajo", type: "kabupaten", province: "Sulawesi Selatan" },
  { id: "7407", value: "Kabupaten Wakatobi", label: "Kabupaten Wakatobi", type: "kabupaten", province: "Sulawesi Tenggara" },
  { id: "9426", value: "Kabupaten Waropen", label: "Kabupaten Waropen", type: "kabupaten", province: "Papua" },
  { id: "1807", value: "Kabupaten Way Kanan", label: "Kabupaten Way Kanan", type: "kabupaten", province: "Lampung" },
  { id: "3312", value: "Kabupaten Wonogiri", label: "Kabupaten Wonogiri", type: "kabupaten", province: "Jawa Tengah" },
  { id: "3307", value: "Kabupaten Wonosobo", label: "Kabupaten Wonosobo", type: "kabupaten", province: "Jawa Tengah" },
  { id: "9416", value: "Kabupaten Yahukimo", label: "Kabupaten Yahukimo", type: "kabupaten", province: "Papua" },
  { id: "9432", value: "Kabupaten Yalimo", label: "Kabupaten Yalimo", type: "kabupaten", province: "Papua" },
  { id: "8171", value: "Kota Ambon", label: "Kota Ambon", type: "kota", province: "Maluku" },
  { id: "6471", value: "Kota Balikpapan", label: "Kota Balikpapan", type: "kota", province: "Kalimantan Timur" },
  { id: "1171", value: "Kota Banda Aceh", label: "Kota Banda Aceh", type: "kota", province: "Aceh" },
  { id: "1871", value: "Kota Bandar Lampung", label: "Kota Bandar Lampung", type: "kota", province: "Lampung" },
  { id: "3273", value: "Kota Bandung", label: "Kota Bandung", type: "kota", province: "Jawa Barat" },
  { id: "3279", value: "Kota Banjar", label: "Kota Banjar", type: "kota", province: "Jawa Barat" },
  { id: "6372", value: "Kota Banjar Baru", label: "Kota Banjar Baru", type: "kota", province: "Kalimantan Selatan" },
  { id: "6371", value: "Kota Banjarmasin", label: "Kota Banjarmasin", type: "kota", province: "Kalimantan Selatan" },
  { id: "2171", value: "Kota Batam", label: "Kota Batam", type: "kota", province: "Kepulauan Riau" },
  { id: "3579", value: "Kota Batu", label: "Kota Batu", type: "kota", province: "Jawa Timur" },
  { id: "7472", value: "Kota Baubau", label: "Kota Baubau", type: "kota", province: "Sulawesi Tenggara" },
  { id: "3275", value: "Kota Bekasi", label: "Kota Bekasi", type: "kota", province: "Jawa Barat" },
  { id: "1771", value: "Kota Bengkulu", label: "Kota Bengkulu", type: "kota", province: "Bengkulu" },
  { id: "5272", value: "Kota Bima", label: "Kota Bima", type: "kota", province: "Nusa Tenggara Barat" },
  { id: "1276", value: "Kota Binjai", label: "Kota Binjai", type: "kota", province: "Sumatera Utara" },
  { id: "7172", value: "Kota Bitung", label: "Kota Bitung", type: "kota", province: "Sulawesi Utara" },
  { id: "3572", value: "Kota Blitar", label: "Kota Blitar", type: "kota", province: "Jawa Timur" },
  { id: "3271", value: "Kota Bogor", label: "Kota Bogor", type: "kota", province: "Jawa Barat" },
  { id: "6474", value: "Kota Bontang", label: "Kota Bontang", type: "kota", province: "Kalimantan Timur" },
  { id: "1375", value: "Kota Bukittinggi", label: "Kota Bukittinggi", type: "kota", province: "Sumatera Barat" },
  { id: "3672", value: "Kota Cilegon", label: "Kota Cilegon", type: "kota", province: "Banten" },
  { id: "3277", value: "Kota Cimahi", label: "Kota Cimahi", type: "kota", province: "Jawa Barat" },
  { id: "3274", value: "Kota Cirebon", label: "Kota Cirebon", type: "kota", province: "Jawa Barat" },
  { id: "5171", value: "Kota Denpasar", label: "Kota Denpasar", type: "kota", province: "Bali" },
  { id: "3276", value: "Kota Depok", label: "Kota Depok", type: "kota", province: "Jawa Barat" },
  { id: "1473", value: "Kota Dumai", label: "Kota Dumai", type: "kota", province: "Riau" },
  { id: "7571", value: "Kota Gorontalo", label: "Kota Gorontalo", type: "kota", province: "Gorontalo" },
  { id: "1278", value: "Kota Gunungsitoli", label: "Kota Gunungsitoli", type: "kota", province: "Sumatera Utara" },
  { id: "3174", value: "Kota Jakarta Barat", label: "Kota Jakarta Barat", type: "kota", province: "DKI Jakarta" },
  { id: "3173", value: "Kota Jakarta Pusat", label: "Kota Jakarta Pusat", type: "kota", province: "DKI Jakarta" },
  { id: "3171", value: "Kota Jakarta Selatan", label: "Kota Jakarta Selatan", type: "kota", province: "DKI Jakarta" },
  { id: "3172", value: "Kota Jakarta Timur", label: "Kota Jakarta Timur", type: "kota", province: "DKI Jakarta" },
  { id: "3175", value: "Kota Jakarta Utara", label: "Kota Jakarta Utara", type: "kota", province: "DKI Jakarta" },
  { id: "1571", value: "Kota Jambi", label: "Kota Jambi", type: "kota", province: "Jambi" },
  { id: "9471", value: "Kota Jayapura", label: "Kota Jayapura", type: "kota", province: "Papua" },
  { id: "3571", value: "Kota Kediri", label: "Kota Kediri", type: "kota", province: "Jawa Timur" },
  { id: "7471", value: "Kota Kendari", label: "Kota Kendari", type: "kota", province: "Sulawesi Tenggara" },
  { id: "7174", value: "Kota Kotamobagu", label: "Kota Kotamobagu", type: "kota", province: "Sulawesi Utara" },
  { id: "5371", value: "Kota Kupang", label: "Kota Kupang", type: "kota", province: "Nusa Tenggara Timur" },
  { id: "1173", value: "Kota Langsa", label: "Kota Langsa", type: "kota", province: "Aceh" },
  { id: "1174", value: "Kota Lhokseumawe", label: "Kota Lhokseumawe", type: "kota", province: "Aceh" },
  { id: "1674", value: "Kota Lubuk Linggau", label: "Kota Lubuk Linggau", type: "kota", province: "Sumatera Selatan" },
  { id: "3577", value: "Kota Madiun", label: "Kota Madiun", type: "kota", province: "Jawa Timur" },
  { id: "3371", value: "Kota Magelang", label: "Kota Magelang", type: "kota", province: "Jawa Tengah" },
  { id: "7371", value: "Kota Makassar", label: "Kota Makassar", type: "kota", province: "Sulawesi Selatan" },
  { id: "3573", value: "Kota Malang", label: "Kota Malang", type: "kota", province: "Jawa Timur" },
  { id: "7171", value: "Kota Manado", label: "Kota Manado", type: "kota", province: "Sulawesi Utara" },
  { id: "5271", value: "Kota Mataram", label: "Kota Mataram", type: "kota", province: "Nusa Tenggara Barat" },
  { id: "1275", value: "Kota Medan", label: "Kota Medan", type: "kota", province: "Sumatera Utara" },
  { id: "1872", value: "Kota Metro", label: "Kota Metro", type: "kota", province: "Lampung" },
  { id: "3576", value: "Kota Mojokerto", label: "Kota Mojokerto", type: "kota", province: "Jawa Timur" },
  { id: "1371", value: "Kota Padang", label: "Kota Padang", type: "kota", province: "Sumatera Barat" },
  { id: "1374", value: "Kota Padang Panjang", label: "Kota Padang Panjang", type: "kota", province: "Sumatera Barat" },
  { id: "1277", value: "Kota Padang Sidempuan", label: "Kota Padang Sidempuan", type: "kota", province: "Sumatera Utara" },
  { id: "1673", value: "Kota Pagar Alam", label: "Kota Pagar Alam", type: "kota", province: "Sumatera Selatan" },
  { id: "6271", value: "Kota Palangka Raya", label: "Kota Palangka Raya", type: "kota", province: "Kalimantan Tengah" },
  { id: "1671", value: "Kota Palembang", label: "Kota Palembang", type: "kota", province: "Sumatera Selatan" },
  { id: "7373", value: "Kota Palopo", label: "Kota Palopo", type: "kota", province: "Sulawesi Selatan" },
  { id: "7271", value: "Kota Palu", label: "Kota Palu", type: "kota", province: "Sulawesi Tengah" },
  { id: "1971", value: "Kota Pangkal Pinang", label: "Kota Pangkal Pinang", type: "kota", province: "Kepulauan Bangka Belitung" },
  { id: "7372", value: "Kota Pare-pare", label: "Kota Pare-pare", type: "kota", province: "Sulawesi Selatan" },
  { id: "1377", value: "Kota Pariaman", label: "Kota Pariaman", type: "kota", province: "Sumatera Barat" },
  { id: "3575", value: "Kota Pasuruan", label: "Kota Pasuruan", type: "kota", province: "Jawa Timur" },
  { id: "1376", value: "Kota Payakumbuh", label: "Kota Payakumbuh", type: "kota", province: "Sumatera Barat" },
  { id: "3375", value: "Kota Pekalongan", label: "Kota Pekalongan", type: "kota", province: "Jawa Tengah" },
  { id: "1471", value: "Kota Pekanbaru", label: "Kota Pekanbaru", type: "kota", province: "Riau" },
  { id: "1273", value: "Kota Pematang Siantar", label: "Kota Pematang Siantar", type: "kota", province: "Sumatera Utara" },
  { id: "6171", value: "Kota Pontianak", label: "Kota Pontianak", type: "kota", province: "Kalimantan Barat" },
  { id: "1672", value: "Kota Prabumulih", label: "Kota Prabumulih", type: "kota", province: "Sumatera Selatan" },
  { id: "3574", value: "Kota Probolinggo", label: "Kota Probolinggo", type: "kota", province: "Jawa Timur" },
  { id: "1172", value: "Kota Sabang", label: "Kota Sabang", type: "kota", province: "Aceh" },
  { id: "3373", value: "Kota Salatiga", label: "Kota Salatiga", type: "kota", province: "Jawa Tengah" },
  { id: "6472", value: "Kota Samarinda", label: "Kota Samarinda", type: "kota", province: "Kalimantan Timur" },
  { id: "1373", value: "Kota Sawah Lunto", label: "Kota Sawah Lunto", type: "kota", province: "Sumatera Barat" },
  { id: "3374", value: "Kota Semarang", label: "Kota Semarang", type: "kota", province: "Jawa Tengah" },
  { id: "3673", value: "Kota Serang", label: "Kota Serang", type: "kota", province: "Banten" },
  { id: "1271", value: "Kota Sibolga", label: "Kota Sibolga", type: "kota", province: "Sumatera Utara" },
  { id: "6172", value: "Kota Singkawang", label: "Kota Singkawang", type: "kota", province: "Kalimantan Barat" },
  { id: "1372", value: "Kota Solok", label: "Kota Solok", type: "kota", province: "Sumatera Barat" },
  { id: "9171", value: "Kota Sorong", label: "Kota Sorong", type: "kota", province: "Papua Barat" },
  { id: "1175", value: "Kota Subulussalam", label: "Kota Subulussalam", type: "kota", province: "Aceh" },
  { id: "3272", value: "Kota Sukabumi", label: "Kota Sukabumi", type: "kota", province: "Jawa Barat" },
  { id: "1572", value: "Kota Sungai Penuh", label: "Kota Sungai Penuh", type: "kota", province: "Jambi" },
  { id: "3578", value: "Kota Surabaya", label: "Kota Surabaya", type: "kota", province: "Jawa Timur" },
  { id: "3372", value: "Kota Surakarta", label: "Kota Surakarta", type: "kota", province: "Jawa Tengah" },
  { id: "3671", value: "Kota Tangerang", label: "Kota Tangerang", type: "kota", province: "Banten" },
  { id: "3674", value: "Kota Tangerang Selatan", label: "Kota Tangerang Selatan", type: "kota", province: "Banten" },
  { id: "1272", value: "Kota Tanjung Balai", label: "Kota Tanjung Balai", type: "kota", province: "Sumatera Utara" },
  { id: "2172", value: "Kota Tanjung Pinang", label: "Kota Tanjung Pinang", type: "kota", province: "Kepulauan Riau" },
  { id: "6571", value: "Kota Tarakan", label: "Kota Tarakan", type: "kota", province: "Kalimantan Utara" },
  { id: "3278", value: "Kota Tasikmalaya", label: "Kota Tasikmalaya", type: "kota", province: "Jawa Barat" },
  { id: "1274", value: "Kota Tebing Tinggi", label: "Kota Tebing Tinggi", type: "kota", province: "Sumatera Utara" },
  { id: "3376", value: "Kota Tegal", label: "Kota Tegal", type: "kota", province: "Jawa Tengah" },
  { id: "8271", value: "Kota Ternate", label: "Kota Ternate", type: "kota", province: "Maluku Utara" },
  { id: "8272", value: "Kota Tidore Kepulauan", label: "Kota Tidore Kepulauan", type: "kota", province: "Maluku Utara" },
  { id: "7173", value: "Kota Tomohon", label: "Kota Tomohon", type: "kota", province: "Sulawesi Utara" },
  { id: "8172", value: "Kota Tual", label: "Kota Tual", type: "kota", province: "Maluku" },
  { id: "3471", value: "Kota Yogyakarta", label: "Kota Yogyakarta", type: "kota", province: "DI Yogyakarta" },
];

/** Lookup cepat by value, dipakai saat menampilkan ulang data tersimpan (mis. di Edit Profile). */
export const REGION_BY_VALUE: Record<string, IndonesiaRegion> = Object.fromEntries(
  INDONESIA_REGIONS.map((r) => [r.value, r])
);

/** Daftar nama provinsi unik, terurut alfabet — dipakai untuk filter wilayah di Leaderboard/Analitik. */
export const INDONESIA_PROVINCES: string[] = Array.from(
  new Set(INDONESIA_REGIONS.map((r) => r.province))
).sort((a, b) => a.localeCompare(b));

/**
 * Pencarian sederhana untuk combobox: cocok di awal kata mana pun dalam label
 * (bukan cuma prefix keseluruhan), supaya mengetik "sleman" atau "kab sleman"
 * sama-sama menemukan "Kabupaten Sleman".
 */
export function searchRegions(query: string, limit = 50): IndonesiaRegion[] {
  const q = query.trim().toLowerCase();
  if (!q) return INDONESIA_REGIONS.slice(0, limit);

  const terms = q.split(/\s+/).filter(Boolean);
  return INDONESIA_REGIONS.filter((r) => {
    const haystack = r.label.toLowerCase();
    return terms.every((t) => haystack.includes(t));
  }).slice(0, limit);
}
